document.form2.ant_codigo2.value='${fld:ant_codigo2@js}';
document.form2.ant_descripcion2.value='${fld:ant_descripcion2@js}';
document.form2.ant_nombres2.value='${fld:ant_nombres2@js}';
document.form2.ant_apellidos2.value='${fld:ant_apellidos2@js}';
document.form2.ant_nombre_corto2.value='${fld:ant_nombre_corto2@js}';
document.form2.ant_tipo_doc_oficial2_name.value='${fld:ant_tipo_doc_oficial2_name@js}';
setComboValue('ant_tipo_doc_oficial2','${fld:ant_tipo_doc_oficial2}','form2');
document.form2.ant_num_doc_oficial2.value='${fld:ant_num_doc_oficial2@js}';
document.form2.ant_fecha_nac2.value='${fld:ant_fecha_nac2@dd-MM-yyyy}';
document.form2.ant_lugar_nac2.value='${fld:ant_lugar_nac2@js}';
document.form2.ant_rif2.value='${fld:ant_rif2@js}';
document.form2.ant_nacionalidad2_name.value='${fld:ant_nacionalidad2_name@js}';
setComboValue('ant_nacionalidad2','${fld:ant_nacionalidad2}','form2');
setComboValue('ant_nacionalizado2','${fld:ant_nacionalizado2}','form2');
document.form2.ant_nacionalizado2_name.value='${fld:ant_nacionalizado2_name@js}';
setComboValue('ant_sexo2','${fld:ant_sexo2}','form2');
document.form2.ant_sexo2_name.value='${fld:ant_sexo2_name@js}';
setComboValue('ant_estado_civil2','${fld:ant_estado_civil2}','form2');
document.form2.ant_estado_civil2_name.value='${fld:ant_estado_civil2_name@js}';
document.form2.ant_direccion2_name.value='${fld:ant_direccion2_name@js}';
setComboValue('ant_direccion2','${fld:ant_direccion2}','form2');
document.form2.ant_cuenta_bancaria2_name.value='${fld:ant_cuenta_bancaria2_name@js}';
setComboValue('ant_cuenta_bancaria2','${fld:ant_cuenta_bancaria2}','form2');
document.form2.ant_contactos2_name.value='${fld:ant_contactos2_name@js}';
setComboValue('ant_contactos2','${fld:ant_contactos2}','form2');
document.form2.ant_num_gaceta2.value='${fld:ant_num_gaceta2@#,###,###}';
document.form2.ant_fecha_gaceta_nac2.value='${fld:ant_fecha_gaceta_nac2@dd-MM-yyyy}';
document.form2.ant_condicion_financiera2_name.value='${fld:ant_condicion_financiera2_name@js}';
setComboValue('ant_condicion_financiera2','${fld:ant_condicion_financiera2}','form2');
document.form2.ant_persona_contacto2.value='${fld:ant_persona_contacto2@js}';
document.form2.ant_observacion2.value='${fld:ant_observacion2@js}';

document.form2.rowindex.value = "${fld:id}";
document.getElementById("saveDetail2").value = "Modificar";
setFocusOnForm("form2");
