select
	smn_base.smn_auxiliar_tipos_servicios.smn_auxiliar_tipos_servicios_id,
	smn_base.smn_auxiliar_tipos_servicios.tts_codigo,
	smn_base.smn_auxiliar_tipos_servicios.tts_descripcion,
	smn_base.smn_auxiliar_tipos_servicios.tts_fecha_registro
from
	smn_base.smn_auxiliar_tipos_servicios
where
	smn_base.smn_auxiliar_tipos_servicios.tts_idioma = '${def:locale}'
order by
	smn_base.smn_auxiliar_tipos_servicios.smn_auxiliar_tipos_servicios_id desc