document.form1.smn_auxiliar_categoria_id_name.value='${fld:aca_tipo_persona_pl0@js}';
document.form1.smn_auxiliar_categoria_id.value='${fld:smn_auxiliar_categoria_id@#,###,###}';
document.form1.atr_codigo.value='${fld:atr_codigo@js}';
document.form1.atr_descripcion.value='${fld:atr_descripcion@js}';
document.form1.atr_comunidad.value='${fld:atr_comunidad@#,###,###}';
document.form1.atr_auxiliar_corporacion.value='${fld:atr_auxiliar_corporacion@#,###,###}';
document.form1.atr_auxiliar_unidad_negocio.value='${fld:atr_auxiliar_unidad_negocio@#,###,###}';
setComboValue('atr_maneja_sucursal','${fld:atr_maneja_sucursal}','form1');
document.form1.atr_razon_social.value='${fld:atr_razon_social@js}';
document.form1.atr_denom_comercial.value='${fld:atr_denom_comercial@js}';
document.form1.atr_beneficiario.value='${fld:atr_beneficiario@js}';
document.form1.atr_tipo_doc_oficial.value='${fld:atr_tipo_doc_oficial@#,###,###}';
document.form1.atr_num_doc_oficial.value='${fld:atr_num_doc_oficial@js}';
setComboValue('atr_clasif_abc','${fld:atr_clasif_abc}','form1');
document.form1.atr_rif.value='${fld:atr_rif@js}';
document.form1.atr_direccion.value='${fld:atr_direccion@#,###,###}';
document.form1.atr_cuenta_bancaria.value='${fld:atr_cuenta_bancaria@#,###,###}';
document.form1.atr_contactos.value='${fld:atr_contactos@#,###,###}';
document.form1.atr_persona_contacto.value='${fld:atr_persona_contacto@js}';
document.form1.atr_representante_legal.value='${fld:atr_representante_legal@js}';
document.form1.atr_benef_pago.value='${fld:atr_benef_pago@js}';
document.form1.atr_cond_pago.value='${fld:atr_cond_pago@#,###,###}';
setComboValue('atr_tipo_facturac','${fld:atr_tipo_facturac}','form1');
document.form1.atr_condicion_financiera.value='${fld:atr_condicion_financiera@#,###,###}';
document.form1.atr_observacion.value='${fld:atr_observacion@js}';
document.form1.id.value='${fld:smn_auxiliar_tercero_id@#,###,###}';
 
document.getElementById("formTitle").innerHTML = "Editar registro";
document.getElementById("grabar").disabled=false;
setFocusOnForm("form1");

