document.form2.atr_codigo2.value='${fld:atr_codigo2@js}';
document.form2.atr_descripcion2.value='${fld:atr_descripcion2@js}';
document.form2.atr_razon_social2.value='${fld:atr_razon_social2@js}';
document.form2.atr_denom_comercial2.value='${fld:atr_denom_comercial2@js}';
document.form2.atr_beneficiario2.value='${fld:atr_beneficiario2@js}';
document.form2.atr_tipo_doc_oficial2_name.value='${fld:atr_tipo_doc_oficial2_name@js}';
setComboValue('atr_tipo_doc_oficial2','${fld:atr_tipo_doc_oficial2}','form2');
document.form2.atr_num_doc_oficial2.value='${fld:atr_num_doc_oficial2@js}';
setComboValue('atr_clasif_abc2','${fld:atr_clasif_abc2}','form2');
document.form2.atr_clasif_abc2_name.value='${fld:atr_clasif_abc2_name@js}';
document.form2.atr_rif2.value='${fld:atr_rif2@js}';
document.form2.atr_direccion2_name.value='${fld:atr_direccion2_name@js}';
setComboValue('atr_direccion2','${fld:atr_direccion2}','form2');
document.form2.atr_cuenta_bancaria2_name.value='${fld:atr_cuenta_bancaria2_name@js}';
setComboValue('atr_cuenta_bancaria2','${fld:atr_cuenta_bancaria2}','form2');
document.form2.atr_contactos2_name.value='${fld:atr_contactos2_name@js}';
setComboValue('atr_contactos2','${fld:atr_contactos2}','form2');
document.form2.atr_persona_contacto2.value='${fld:atr_persona_contacto2@js}';
document.form2.atr_representante_legal2.value='${fld:atr_representante_legal2@js}';
document.form2.atr_benef_pago2.value='${fld:atr_benef_pago2@js}';
document.form2.atr_cond_pago2_name.value='${fld:atr_cond_pago2_name@js}';
setComboValue('atr_cond_pago2','${fld:atr_cond_pago2}','form2');
setComboValue('atr_tipo_facturac2','${fld:atr_tipo_facturac2}','form2');
document.form2.atr_tipo_facturac2_name.value='${fld:atr_tipo_facturac2_name@js}';
document.form2.atr_condicion_financiera2_name.value='${fld:atr_condicion_financiera2_name@js}';
setComboValue('atr_condicion_financiera2','${fld:atr_condicion_financiera2}','form2');
document.form2.atr_observacion2.value='${fld:atr_observacion2@js}';

document.form2.rowindex.value = "${fld:id}";
document.getElementById("saveDetail2").value = "Modificar";
setFocusOnForm("form2");
