INSERT INTO smn_base.smn_auxiliar_contacto
(
	smn_auxiliar_contacto_id,
	acn_telefono_fijo,
	acn_telefono_movil,
	acn_email,
	acn_facebook,
	acn_linkedin,
	acn_twitter,
	acn_swift,
	acn_idioma,
	acn_usuario,
	acn_fecha_registro,
	acn_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_auxiliar_contacto},
	${fld:acn_telefono_fijo},
	${fld:acn_telefono_movil},
	${fld:acn_email},
	${fld:acn_facebook},
	${fld:acn_linkedin},
	${fld:acn_twitter},
	${fld:acn_swift},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
