INSERT INTO smn_base.smn_usuarios
(
	smn_usuarios_id,
	smn_entidades_id,
	usr_usuario_id,
	usr_nombres,
	usr_apellidos,
	usr_nacionalidad,
	usr_nro_doc_identidad,
	usr_nro_id_fiscal,
	usr_direccion,
	usr_email,
	usr_telefono_fijo,
	usr_telefono_movil,
	usr_idioma,
	usr_usuario,
	usr_fecha_registro,
	usr_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_usuarios},
	${fld:smn_entidades_id},
	${fld:usr_usuario_id},
	${fld:usr_nombres},
	${fld:usr_apellidos},
	${fld:usr_nacionalidad},
	${fld:usr_nro_doc_identidad},
	${fld:usr_nro_id_fiscal},
	${fld:usr_direccion},
	${fld:usr_email},
	${fld:usr_telefono_fijo},
	${fld:usr_telefono_movil},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
