select
		smn_base.smn_tipo_prestadores_servicios.smn_tipo_prestadores_servicios_id,
	smn_base.smn_tipo_prestadores_servicios.tps_codigo,
	smn_base.smn_tipo_prestadores_servicios.tps_descripcion,
	smn_base.smn_tipo_prestadores_servicios.tps_idioma,
	smn_base.smn_tipo_prestadores_servicios.tps_usuario,
	smn_base.smn_tipo_prestadores_servicios.tps_fecha_registro,
	smn_base.smn_tipo_prestadores_servicios.tps_hora
	
from
	smn_base.smn_tipo_prestadores_servicios
