INSERT INTO smn_base.smn_conexiones
(
	smn_conexiones_bd_id,
	con_sistema,
	con_descripcion,
	smn_entidad_rf,
	smn_sucursal_rf,
	con_ip_servidor,
	con_hostname_instancia,
	con_nombre_bd,
	con_usuario_bd,
	con_clave_bd,
	con_puerto_bd,
	con_estatus,
	con_vigencia,
	con_idioma,
	con_usuario,
	con_fecha_registro,
	con_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_conexiones},
	${fld:con_sistema},
	${fld:con_descripcion},
	${fld:smn_entidad_rf},
	${fld:smn_sucursal_rf},
	${fld:con_ip_servidor},
	${fld:con_hostname_instancia},
	${fld:con_nombre_bd},
	${fld:con_usuario_bd},
	${fld:con_clave_bd},
	${fld:con_puerto_bd},
	${fld:con_estatus},
	${fld:con_vigencia},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
