INSERT INTO smn_base.smn_estructura_codigo
(
	smn_estructura_codigo_id,
	smn_modulos_id,
	eco_codigo,
	eco_nombre,
	eco_niveles,
	eco_mascara,
	eco_separador,
	eco_idioma,
	eco_usuario,
	eco_fecha_registro,
	eco_hora,
	smn_entidad_rf
)
VALUES
(
	${seq:currval@smn_base.seq_smn_estructura_codigo},
	${fld:smn_modulos_id},
	${fld:eco_codigo},
	${fld:eco_nombre},
	${fld:eco_niveles},
	${fld:eco_mascara},
	${fld:eco_separador},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_entidad_rf}
)
