select
		smn_base.smn_rel_item_desc_retenc.smn_rel_item_desc_retenc_id,
	smn_base.smn_descuentos_retenciones.smn_descuentos_retenciones_id,
	smn_base.smn_descuentos_retenciones.dyr_codigo as dyr_codigo_pl0,
	smn_base.smn_item.smn_item_id,
	smn_base.smn_item.itm_codigo as itm_codigo_pl1,
select
		smn_base.smn_rel_item_desc_retenc.smn_rel_item_desc_retenc_id,
select
		smn_base.smn_rel_item_desc_retenc.smn_rel_item_desc_retenc_id,
	smn_base.smn_rel_item_desc_retenc.smn_descuentos_retenciones_id,
	smn_base.smn_rel_item_desc_retenc.smn_item_id,
	smn_base.smn_rel_item_desc_retenc.rid_idioma,
	smn_base.smn_rel_item_desc_retenc.rid_usuario,
	smn_base.smn_rel_item_desc_retenc.rid_fecha_registro,
	smn_base.smn_rel_item_desc_retenc.rid_hora,
		smn_base.smn_rel_item_desc_retenc.smn_rel_item_desc_retenc_id
	
from
	smn_base.smn_descuentos_retenciones,
	smn_base.smn_item,
	smn_base.smn_rel_item_desc_retenc
where
	smn_base.smn_descuentos_retenciones.smn_descuentos_retenciones_id=smn_base.smn_rel_item_desc_retenc.smn_descuentos_retenciones_id and
	smn_base.smn_item.smn_item_id=smn_base.smn_rel_item_desc_retenc.smn_item_id
order by
		smn_rel_item_desc_retenc_id
