select
	'' as efi_codigo,
	'' as efi_nombre,
	'' as efi_direccion,
	'' as efi_telefono_fijo,
	'' as efi_telefono_movil,
	'' as efi_codigo_aba,
	'' as efi_codigo_swift,
	'' as efi_req_banco_intermediario_combo,
	'' as efi_banco_intermediario,
	'' as efi_routing,
	'' as efi_contacto,
	'' as efi_fecha_registro,
	'' as efi_direccion_reference,
	'' as efi_req_banco_intermediario_combo_reference,
	'' as efi_banco_intermediario_reference
