select
		smn_base.smn_respuesta.smn_cuestionario_id,
	smn_base.smn_respuesta.smn_seccion_id,
	smn_base.smn_respuesta.smn_pregunta_id,
	smn_base.smn_respuesta.smn_tipo_variable_id,
	smn_base.smn_respuesta.smn_tipo_respuesta_id,
	smn_base.smn_respuesta.smn_variable_id,
	smn_base.smn_respuesta.res_texto_respuesta,
	smn_base.smn_respuesta.cue_fecha_registro,
	smn_base.smn_respuesta.smn_cuestionario_id,
	smn_base.smn_respuesta.smn_seccion_id,
	smn_base.smn_respuesta.smn_pregunta_id,
	smn_base.smn_respuesta.smn_tipo_variable_id,
	smn_base.smn_respuesta.smn_tipo_respuesta_id,
	smn_base.smn_respuesta.smn_variable_id,
	smn_base.smn_respuesta.res_texto_respuesta,
	smn_base.smn_respuesta.cue_fecha_registro
from
	smn_base.smn_respuesta 
where
	smn_base.smn_respuesta.smn_respuesta_id = ${fld:id}
