INSERT INTO smn_base.smn_entidades
(
	smn_entidades_id,
	ent_codigo,
	ent_comunidad,
	ent_corporacion,
	ent_moneda,
	ent_sector_economico,
	ent_descripcion_corta,
	ent_descripcion_larga,
	ent_nro_id_fiscal,
	ent_direccion,
	ent_contacto,
	ent_telefono_fijo,
	ent_telefono_movil,
	ent_email,
	ent_act_economica,
	ent_idioma,
	ent_usuario,
	ent_fecha_registro,
	ent_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_entidades},
	${fld:ent_codigo},
	${fld:ent_comunidad},
	${fld:ent_corporacion},
	${fld:ent_moneda},
	${fld:ent_sector_economico},
	${fld:ent_descripcion_corta},
	${fld:ent_descripcion_larga},
	${fld:ent_nro_id_fiscal},
	${fld:ent_direccion},
	${fld:ent_contacto},
	${fld:ent_telefono_fijo},
	${fld:ent_telefono_movil},
	${fld:ent_email},
	${fld:ent_act_economica},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
