select
	smn_seguridad.s_application.app_alias,
	smn_seguridad.s_menu.title,
	smn_base.smn_menu_traduccion.smn_menu_traduccion_id,
	smn_base.smn_menu_traduccion.mnt_app_id,
	smn_base.smn_menu_traduccion.mnt_menu_id,
	smn_base.smn_menu_traduccion.mnt_title,
	smn_base.smn_menu_traduccion.mnt_locale,
	smn_base.smn_menu_traduccion.mnt_fecha_registro
from 
	smn_seguridad.s_application,
	smn_seguridad.s_menu,
	smn_base.smn_menu_traduccion
where
	smn_base.smn_menu_traduccion.mnt_app_id=smn_seguridad.s_application.app_id
and
	smn_base.smn_menu_traduccion.mnt_menu_id=smn_seguridad.s_menu.menu_id
and
	smn_base.smn_menu_traduccion.smn_menu_traduccion_id=${fld:id}
order by 
	smn_base.smn_menu_traduccion.smn_menu_traduccion_id
