select
	'' as eor_centro_costo,
	'' as eor_centro_costo_reference,
	'' as eor_auxiliar,
	'' as eor_auxiliar_reference,
	'' as eor_hora,
	'' as smn_configuracion_estructura_id,
	'' as smn_configuracion_estructura_id_reference,
	'' as eor_clase_auxiliar,
	'' as eor_clase_auxiliar_reference,
	'' as eor_idioma,
	'' as smn_estructura_organizacional_id,
	'' as eor_usuario,
	'' as eor_codigo,
	'' as eor_nombre,
	'' as eor_fecha_registro