select	
	smn_base.smn_auxiliar_tipos_servicios.smn_auxiliar_tipos_servicios_id, 
	smn_base.smn_auxiliar_tipos_servicios.tts_codigo as tts_codigo_pl0,
	smn_base.smn_auxiliar_areas_servicios.smn_auxiliar_tipos_servicios_id,
	smn_base.smn_auxiliar_areas_servicios.tse_codigo,
	smn_base.smn_auxiliar_areas_servicios.tse_descripcion,
	smn_base.smn_auxiliar_areas_servicios.tse_auxiliar,
	smn_base.smn_auxiliar_areas_servicios.tse_auxiliar_sucursal,
	smn_base.smn_auxiliar_areas_servicios.tse_auxiliar_unidad_negocio,
	smn_base.smn_auxiliar_areas_servicios.tse_fecha_registro,
	smn_base.smn_auxiliar_areas_servicios.smn_auxiliar_areas_servicios_id

from
	smn_base.smn_auxiliar_tipos_servicios,
	smn_base.smn_auxiliar_areas_servicios
where
	smn_auxiliar_areas_servicios_id is not null	
and 	smn_base.smn_auxiliar_tipos_servicios.smn_auxiliar_tipos_servicios_id=smn_base.smn_auxiliar_areas_servicios.smn_auxiliar_tipos_servicios_id 
	 	${filter}
order by 
	smn_auxiliar_areas_servicios_id