select
	smn_base.smn_auxiliar_areas_servicios.smn_auxiliar_areas_servicios_id,
	smn_base.smn_auxiliar_areas_servicios.tse_codigo as tse_codigo_pl0,
	smn_base.smn_auxiliar_unidades_servicios.smn_auxiliar_areas_servicios_id,
	smn_base.smn_auxiliar_unidades_servicios.tns_codigo,
	smn_base.smn_auxiliar_unidades_servicios.tns_descripcion,
	smn_base.smn_auxiliar_unidades_servicios.tns_fecha_registro,
	smn_base.smn_auxiliar_unidades_servicios.smn_auxiliar_unidades_servicios_id
from
	smn_base.smn_auxiliar_areas_servicios,
	smn_base.smn_auxiliar_unidades_servicios
where
	smn_auxiliar_unidades_servicios_id is not null
and 	
	smn_base.smn_auxiliar_areas_servicios.smn_auxiliar_areas_servicios_id=smn_base.smn_auxiliar_unidades_servicios.smn_auxiliar_areas_servicios_id
and
	smn_base.smn_auxiliar_unidades_servicios.tns_idioma = '${def:locale}'
and
	smn_base.smn_auxiliar_unidades_servicios.tns_usuario = '${def:user}'
	${filter}
order by
	smn_base.smn_auxiliar_unidades_servicios.smn_auxiliar_unidades_servicios_id desc
