INSERT INTO smn_base.smn_prestadores_servicios
(
	smn_prestadores_servicios_id,
	prs_codigo,
	prs_descripcion,
	prs_area_servicio,
	prs_unidad_servicio,
	prs_clase_auxiliar,
	prs_auxiliar,
	smn_grupos_prestadores,
	prs_direccion,
	prs_telefono_fijo,
	prs_telefono_movil,
	prs_frecuencia,
	prs_idioma,
	prs_usuario,
	prs_fecha_registro,
	prs_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_prestadores_servicios},
	${fld:prs_codigo},
	${fld:prs_descripcion},
	${fld:prs_area_servicio},
	${fld:prs_unidad_servicio},
	${fld:prs_clase_auxiliar},
	${fld:prs_auxiliar},
	${fld:smn_grupos_prestadores},
	${fld:prs_direccion},
	${fld:prs_telefono_fijo},
	${fld:prs_telefono_movil},
	${fld:prs_frecuencia},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
