INSERT INTO smn_base.smn_sucursales
(
	smn_sucursales_id,
	suc_empresa,
	suc_codigo,
	suc_nombre,
	suc_unidad_negocio,
	suc_maneja_area_servicio,
	suc_responsable,
	suc_direccion,
	suc_telefono_fijo,
	suc_telefono_movil,
	suc_email,
	suc_idioma,
	suc_usuario,
	suc_fecha_registro,
	suc_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_sucursales},
	${fld:suc_empresa},
	${fld:suc_codigo},
	${fld:suc_nombre},
	${fld:suc_unidad_negocio},
	${fld:suc_maneja_area_servicio},
	${fld:suc_responsable},
	${fld:suc_direccion},
	${fld:suc_telefono_fijo},
	${fld:suc_telefono_movil},
	${fld:suc_email},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
