INSERT INTO smn_base.smn_servicios_componentes
(
	smn_servicios_componentes_id,
	smn_servicios_id,
	smn_componentes_id,
	sec_cantidad,
	smn_entidades_rf,
	smn_sucursales_rf,
	smn_areas_servicios_rf,
	smn_unidades_servicios_rf,
	sec_porcentaje,
	sec_gastos,
	smn_clase_auxiliar_rf
)
VALUES
(
	${seq:currval@smn_base.seq_smn_servicios_componentes},
	${fld:smn_servicios_id},
	${fld:smn_componentes_id},
	${fld:sec_cantidad},
	${fld:smn_entidades_rf},
	${fld:smn_sucursales_rf},
	${fld:smn_areas_servicios_rf},
	${fld:smn_unidades_servicios_rf},
	${fld:sec_porcentaje},
	${fld:sec_gastos},
	${fld:smn_clase_auxiliar_rf}
)
