INSERT INTO smn_base.smn_rel_afijo_cod_impuesto
(
	smn_rel_afijo_cod_impuesto_id,
	smn_afijo_id,
	smn_codigos_impuestos_id,
	rai_idioma,
	rai_usuario,
	rai_fecha_registro,
	rai_hora
)
VALUES
(
	${seq:currval@smn_base.seq_smn_rel_afijo_cod_impuesto},
	${fld:smn_afijo_id},
	${fld:smn_codigos_impuestos_id},
	'${def:locale}',
	'${def:user}',
	'${def:date}',
	'${def:time}'
)
