select
	smn_base.smn_prestadores_servicios.prs_codigo,
	smn_base.smn_prestadores_servicios.prs_descripcion,
	smn_base.smn_areas_servicios.ase_descripcion,
	smn_base.smn_auxiliar_prestador_servicio.aps_descripcion as smn_item,
	smn_base.smn_clase_auxiliar.cla_codigo||'-'||smn_base.smn_clase_auxiliar.cla_nombre as smn_clase_auxiliar_rf,
	smn_base.smn_unidades_servicios.uns_descripcion,
	smn_base.smn_prestadores_servicios.prs_unidad_servicio,
	smn_base.smn_prestadores_servicios.prs_orden_atencion,
	smn_base.smn_prestadores_servicios.prs_estatus,
	smn_base.smn_prestadores_servicios.prs_fecha_inicio_estatus,
	smn_base.smn_prestadores_servicios.prs_fecha_final_estatus,
	smn_base.smn_prestadores_servicios.prs_frecuencia,
	smn_base.smn_prestadores_servicios.prs_fecha_registro,
	smn_base.smn_prestadores_servicios.smn_prestadores_servicios_id
from
	smn_base.smn_prestadores_servicios
	left outer join smn_base.smn_areas_servicios on smn_base.smn_areas_servicios.smn_areas_servicios_id = smn_base.smn_prestadores_servicios.prs_area_servicio
	left outer join smn_base.smn_auxiliar_prestador_servicio on smn_base.smn_auxiliar_prestador_servicio.smn_auxiliar_prestador_servicio_id = smn_base.smn_prestadores_servicios.prs_auxiliar
	left outer join smn_base.smn_clase_auxiliar on smn_base.smn_clase_auxiliar.smn_clase_auxiliar_id = smn_base.smn_prestadores_servicios.prs_clase_auxiliar
	left outer join smn_base.smn_unidades_servicios on smn_base.smn_unidades_servicios.smn_unidades_servicios_id = smn_base.smn_prestadores_servicios.prs_unidad_servicio
where
	smn_prestadores_servicios_id = ${fld:id}
