INSERT INTO smn_base.smn_baremos_detalle
(
	smn_baremos_detalle_id,
	smn_baremos_id,
	smn_servicios_rf,
	bad_tipo_componente,
	smn_clase_auxiliar_rf,
	smn_item_rf,
	smn_almacen_rf,
	bad_cantidad,
	bad_precio_moneda_local,
	smn_moneda_rf,
	bad_precio_moneda_alterna,
	smn_descuento_rf,
	bad_estatus,
	bad_idioma,
	bad_usuario,
	bad_fecha_registro,
	bad_hora,
	bad_forma_calculo
)
VALUES
(
	${seq:currval@smn_base.seq_smn_baremos_detalle},
	${fld:smn_baremos_id},
	${fld:smn_servicios_rf},
	${fld:bad_tipo_componente},
	${fld:smn_clase_auxiliar_rf},
	${fld:smn_item_rf},
	${fld:smn_almacen_rf},
	${fld:bad_cantidad},
	${fld:bad_precio_moneda_local},
	${fld:smn_moneda_rf},
	${fld:bad_precio_moneda_alterna},
	${fld:smn_descuento_rf},
	${fld:bad_estatus},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:bad_forma_calculo}
)
